try {
    console.log(x);

}
catch (e) {

}